knpu_oauth2_client:
    clients:
        line:
            type: generic
            provider_class: App\Security\OAuth2\Client\Provider\Line
            client_id: '%env(LINE_CLIENT_ID)%'
            client_secret: '%env(LINE_CLIENT_SECRET)%'
            redirect_route: connect_line_callback